# Generated by Django 3.2.23 on 2023-11-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ldr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('luminosidade', models.FloatField(default='00', max_length=200)),
                ('media_luminosidade', models.FloatField(default='30', max_length=200)),
                ('unidade_medida', models.CharField(default='Lux', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NivelAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.FloatField(default='00', max_length=200)),
                ('nivel_minimo', models.FloatField(default='30', max_length=200)),
                ('unidade_medida', models.CharField(default='Centímetros', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tds', models.FloatField(default='00', max_length=200)),
                ('media_tds', models.FloatField(default='30', max_length=200)),
                ('unidade_medida', models.CharField(default='Ppm', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperaturaAquario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField(default='00', max_length=200)),
                ('unidade_medida', models.CharField(default='Graus', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemperaturaPlantas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField(default='00', max_length=200)),
                ('unidade_medida', models.CharField(default='Graus', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default='00', max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Umidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('umidade', models.FloatField(default='00', max_length=200)),
                ('unidade_medida', models.CharField(default='Porcentagem', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
