# Generated by Django 3.2.23 on 2023-11-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.AlterField(
            model_name='ldr',
            name='unidade_medida',
            field=models.CharField(default='lux', max_length=50),
        ),
        migrations.AlterField(
            model_name='nivelagua',
            name='unidade_medida',
            field=models.CharField(default='centímetros', max_length=50),
        ),
        migrations.AlterField(
            model_name='tds',
            name='unidade_medida',
            field=models.CharField(default='ppm', max_length=50),
        ),
        migrations.AlterField(
            model_name='temperaturaaquario',
            name='unidade_medida',
            field=models.CharField(default='graus', max_length=50),
        ),
        migrations.AlterField(
            model_name='temperaturaplantas',
            name='unidade_medida',
            field=models.CharField(default='graus', max_length=50),
        ),
        migrations.AlterField(
            model_name='umidade',
            name='unidade_medida',
            field=models.CharField(default='porcentagem', max_length=50),
        ),
    ]
